# Generated by Django 4.2 on 2023-04-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYUVoiceapp', '0002_alter_coursereview_title_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='content',
        ),
        migrations.AddField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
