# Generated by Django 4.2 on 2023-04-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NYUVoiceapp', '0003_remove_rate_content_rate_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='title',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
